In [4]:
import pandas as pd

In [6]:
df_1 = pd.read_csv("final31.csv")
df_1.describe()

,tire_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,percent_hardness,mileage_km,rem_dist_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,71.533882,45631.578947,18480.263158
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,4.044737,14272.041956,7804.711088
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,66.010000,20000.000000,7000.000000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,67.630000,35000.000000,12000.000000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,70.720000,45000.000000,18000.000000
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,75.850000,55000.000000,25000.000000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,76.900000,70000.000000,32000.000000

In [7]:
df_1.rename(columns = {"tire_pressure_psi":"tyre_pressure_psi"},inplace = True)

In [8]:
df_1.describe()

,tyre_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,percent_hardness,mileage_km,rem_dist_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,71.533882,45631.578947,18480.263158
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,4.044737,14272.041956,7804.711088
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,66.010000,20000.000000,7000.000000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,67.630000,35000.000000,12000.000000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,70.720000,45000.000000,18000.000000
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,75.850000,55000.000000,25000.000000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,76.900000,70000.000000,32000.000000

In [9]:
total_life_km = []
for i in df_1.total_life_km:
    total_life_km.append(i)

In [10]:
df_1.drop(columns = ["total_life_km","rem_dist_km"],inplace = True)
df_1["total_life_km"] = total_life_km
df_1.describe()

,tyre_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,percent_hardness,mileage_km,total_life_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,71.533882,45631.578947,64111.842105
std,2.680427,15.525498,12.381714,50.181572,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,4.044737,14272.041956,21823.054017
min,27.000000,40.000000,90.000000,350.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,66.010000,20000.000000,28000.000000
25%,30.000000,50.000000,101.250000,375.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,67.630000,35000.000000,47000.000000
50%,32.000000,65.000000,112.750000,400.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,70.720000,45000.000000,65000.000000
75%,34.000000,75.000000,126.750000,450.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,75.850000,55000.000000,80000.000000
max,37.000000,100.000000,129.250000,500.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,76.900000,70000.000000,102000.000000

In [11]:
df_1.to_csv("last_1.csv",index = False)

In [13]:
run_km_per_yr = []
for i in range(0,152):
    run_km_per_yr.append(df_1.mileage_km[i]/df_1.tyre_age_yrs[i])

In [ ]:
df_1.drop("")

In [14]:
# GRADIENT BOOSTING MACHINE - REGRESSION
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Step 1: Read the data from the CSV file
def read_data(filename):
    data = pd.read_csv(filename)
    return data

# Step 2: Split the data into features (X) and target (y)
def split_data(data):
    X = data.iloc[:, :-1]
    y = data.iloc[:, -1]
    return X, y

# Step 3: Split the data into training and testing sets
def split_train_test(X, y, test_size=0.2, random_state=42):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
    return X_train, X_test, y_train, y_test

# Step 4: Create and train the Gradient Boosting Machine Regression model
def train_gradient_boosting_regression(X_train, y_train):
    model = GradientBoostingRegressor()
    model.fit(X_train, y_train)
    return model

# Step 5: Make predictions using the trained model
def make_predictions(model, X_test):
    y_pred = model.predict(X_test)
    return y_pred

# Step 6: Evaluate the model's performance
def evaluate_model(y_test, y_pred):
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return mse, r2

if __name__ == "__main__":
    # Step 1: Read the data from the CSV file
    data = read_data("last_1.csv")

    # Step 2: Split the data into features (X) and target (y)
    X, y = split_data(data)

    # Step 3: Split the data into training and testing sets
    X_train, X_test, y_train, y_test = split_train_test(X, y)

    # Step 4: Create and train the Gradient Boosting Machine Regression model
    model = train_gradient_boosting_regression(X_train, y_train)

    # Step 5: Make predictions using the trained model
    y_pred = make_predictions(model, X_test)

    # Step 6: Evaluate the model's performance
    mse, r2 = evaluate_model(y_test, y_pred)

    print("Mean Squared Error:", mse)
    print("R-squared:", r2)

Mean Squared Error: 1.4076104387858765
R-squared: 0.9999999958949216