In [1]:
import pandas as pd

In [2]:
df_1 = pd.read_csv("final27.csv")

In [3]:
df_1.describe()

          load_ind   speed_ind  recomm_tyre_press
count   152.000000  152.000000         152.000000
mean    498.289474   98.750000          33.131579
std     200.689627   19.910811           2.382842
min     272.000000   80.000000          30.000000
25%     335.000000   80.000000          31.000000
50%     468.500000   90.000000          35.000000
75%     600.000000  110.000000          35.000000
max    1030.000000  150.000000          36.000000

In [4]:
df_2 = pd.read_csv("final29.csv")

In [5]:
df_2.describe()

,tyre_sdwl_mm,tyre_age_yrs,tyre_width_mm,tread_depth_alwd_mm,tp_ip_psi,sp_ip_kmph,ld_ip_kg,total_life_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,113.766447,3.197368,212.631579,4.430921,1.296053,35.427632,78.881579,64111.842105
std,12.381714,1.255660,17.443830,0.525538,2.324186,15.925573,175.225113,21823.054017
min,90.000000,1.000000,185.000000,3.600000,-7.000000,5.000000,-78.000000,28000.000000
25%,101.250000,2.000000,195.000000,4.100000,0.000000,30.000000,-60.000000,47000.000000
50%,112.750000,3.000000,205.000000,4.400000,1.500000,35.000000,30.000000,65000.000000
75%,126.750000,4.000000,225.000000,4.800000,3.000000,50.000000,112.000000,80000.000000
max,129.250000,5.000000,235.000000,5.600000,5.000000,80.000000,580.000000,102000.000000

In [6]:
total_life_km = []
tyre_age_yrs = []
for i in range(0,len(df_2)):
    total_life_km.append(df_2.total_life_km[i])
    tyre_age_yrs.append(df_2.tyre_age_yrs[i])
len(total_life_km)

152

In [7]:
len(tyre_age_yrs)

152

In [8]:
df_1.drop(columns=["recomm_tyre_press"],inplace = True)

In [9]:
df_1["tyre_age_yrs"] = tyre_age_yrs
df_1["total_life_km"] = total_life_km
df_1.describe()

          load_ind   speed_ind  tyre_age_yrs  total_life_km
count   152.000000  152.000000    152.000000     152.000000
mean    498.289474   98.750000      3.197368   64111.842105
std     200.689627   19.910811      1.255660   21823.054017
min     272.000000   80.000000      1.000000   28000.000000
25%     335.000000   80.000000      2.000000   47000.000000
50%     468.500000   90.000000      3.000000   65000.000000
75%     600.000000  110.000000      4.000000   80000.000000
max    1030.000000  150.000000      5.000000  102000.000000

In [10]:
df_1.to_csv("mid_1.csv",index = False)

In [11]:
# K - means clustering 
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Step 1: Load the data from the CSV file
data = pd.read_csv("mid_1.csv")

# Step 2: Prepare the data for clustering
X = data.values  # Convert DataFrame to a NumPy array for clustering

# Step 3: Create and fit the KMeans model with 2 clusters
num_clusters = 2
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
kmeans.fit(X)

# Step 4: Get the cluster assignments
cluster_labels = kmeans.labels_

# Step 5: Print the indexes belonging to each cluster
for cluster_num in range(num_clusters):
    cluster_indices = np.where(cluster_labels == cluster_num)[0]
    print(f"Data points in cluster {cluster_num}: {cluster_indices}")

# Step 6: Calculate and print the silhouette score for 2 clusters
silhouette_avg = silhouette_score(X, cluster_labels)
print(f"Silhouette Score for 2 clusters: {silhouette_avg:.4f}")

Data points in cluster 0: [  0   3   4   7   8  12  13  15  18  19  23  24  26  29  30  32  35  36
  39  40  42  45  46  49  50  52  55  56  59  60  62  65  66  69  70  72
  75  76  79  80  82  85  86  89  90  92  95  96  99 100 102 105 106 109
 110 112 115 116 119 120 122 125 126 129 130 132 135 136 139 140 142 145
 146 149 150]
Data points in cluster 1: [  1   2   5   6   9  10  11  14  16  17  20  21  22  25  27  28  31  33
  34  37  38  41  43  44  47  48  51  53  54  57  58  61  63  64  67  68
  71  73  74  77  78  81  83  84  87  88  91  93  94  97  98 101 103 104
 107 108 111 113 114 117 118 121 123 124 127 128 131 133 134 137 138 141
 143 144 147 148 151]
Silhouette Score for 2 clusters: 0.6431

In [12]:
# K means clustering
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Step 1: Load the data from the CSV file
data = pd.read_csv("mid_1.csv")

# Step 2: Prepare the data for clustering
X = data.values  # Convert DataFrame to a NumPy array for clustering

# Step 3: Create and fit the KMeans model with 2 clusters
num_clusters = 2
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
kmeans.fit(X)

# Step 4: Get the cluster assignments and cluster centers
cluster_labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_

# Step 5: Print the indexes belonging to each cluster and their percentage of belongingness to cluster 1
for i, cluster_label in enumerate(cluster_labels):
    cluster_center_1 = cluster_centers[0]  # Center of cluster 1
    cluster_center_2 = cluster_centers[1]  # Center of cluster 2
    distance_to_cluster_1 = np.linalg.norm(X[i] - cluster_center_1)  # Distance to cluster 1 center
    distance_to_cluster_2 = np.linalg.norm(X[i] - cluster_center_2)  # Distance to cluster 2 center
    percentage_cluster_1 = distance_to_cluster_1 / (distance_to_cluster_1 + distance_to_cluster_2) * 100
    print(f"Index {i}: Belongs {percentage_cluster_1:.2f}% to cluster 1")

# Step 6: Calculate and print the silhouette score for 2 clusters
silhouette_avg = silhouette_score(X, cluster_labels)
print(f"\nSilhouette Score for 2 clusters: {silhouette_avg:.4f}")

Index 0: Belongs 26.37% to cluster 1
Index 1: Belongs 93.01% to cluster 1
Index 2: Belongs 85.89% to cluster 1
Index 3: Belongs 5.06% to cluster 1
Index 4: Belongs 26.37% to cluster 1
Index 5: Belongs 93.01% to cluster 1
Index 6: Belongs 85.89% to cluster 1
Index 7: Belongs 5.06% to cluster 1
Index 8: Belongs 23.85% to cluster 1
Index 9: Belongs 55.69% to cluster 1
Index 10: Belongs 53.02% to cluster 1
Index 11: Belongs 82.19% to cluster 1
Index 12: Belongs 10.70% to cluster 1
Index 13: Belongs 20.57% to cluster 1
Index 14: Belongs 83.33% to cluster 1
Index 15: Belongs 26.37% to cluster 1
Index 16: Belongs 93.01% to cluster 1
Index 17: Belongs 85.89% to cluster 1
Index 18: Belongs 5.06% to cluster 1
Index 19: Belongs 23.85% to cluster 1
Index 20: Belongs 55.69% to cluster 1
Index 21: Belongs 53.02% to cluster 1
Index 22: Belongs 82.19% to cluster 1
Index 23: Belongs 10.70% to cluster 1
Index 24: Belongs 20.57% to cluster 1
Index 25: Belongs 83.33% to cluster 1
Index 26: Belongs 23.70% to cluster 1
Index 27: Belongs 88.86% to cluster 1
Index 28: Belongs 93.00% to cluster 1
Index 29: Belongs 23.85% to cluster 1
Index 30: Belongs 5.06% to cluster 1
Index 31: Belongs 71.68% to cluster 1
Index 32: Belongs 10.70% to cluster 1
Index 33: Belongs 74.59% to cluster 1
Index 34: Belongs 74.35% to cluster 1
Index 35: Belongs 39.70% to cluster 1
Index 36: Belongs 23.70% to cluster 1
Index 37: Belongs 88.86% to cluster 1
Index 38: Belongs 93.00% to cluster 1
Index 39: Belongs 23.85% to cluster 1
Index 40: Belongs 5.06% to cluster 1
Index 41: Belongs 71.68% to cluster 1
Index 42: Belongs 10.70% to cluster 1
Index 43: Belongs 74.59% to cluster 1
Index 44: Belongs 74.35% to cluster 1
Index 45: Belongs 39.70% to cluster 1
Index 46: Belongs 23.70% to cluster 1
Index 47: Belongs 88.86% to cluster 1
Index 48: Belongs 93.00% to cluster 1
Index 49: Belongs 23.85% to cluster 1
Index 50: Belongs 5.06% to cluster 1
Index 51: Belongs 71.68% to cluster 1
Index 52: Belongs 10.70% to cluster 1
Index 53: Belongs 74.59% to cluster 1
Index 54: Belongs 74.35% to cluster 1
Index 55: Belongs 39.70% to cluster 1
Index 56: Belongs 23.70% to cluster 1
Index 57: Belongs 88.86% to cluster 1
Index 58: Belongs 93.00% to cluster 1
Index 59: Belongs 23.85% to cluster 1
Index 60: Belongs 5.06% to cluster 1
Index 61: Belongs 71.68% to cluster 1
Index 62: Belongs 10.70% to cluster 1
Index 63: Belongs 74.59% to cluster 1
Index 64: Belongs 74.35% to cluster 1
Index 65: Belongs 39.70% to cluster 1
Index 66: Belongs 23.70% to cluster 1
Index 67: Belongs 88.86% to cluster 1
Index 68: Belongs 93.00% to cluster 1
Index 69: Belongs 23.85% to cluster 1
Index 70: Belongs 5.06% to cluster 1
Index 71: Belongs 71.68% to cluster 1
Index 72: Belongs 10.70% to cluster 1
Index 73: Belongs 74.59% to cluster 1
Index 74: Belongs 74.35% to cluster 1
Index 75: Belongs 39.70% to cluster 1
Index 76: Belongs 23.70% to cluster 1
Index 77: Belongs 88.86% to cluster 1
Index 78: Belongs 93.00% to cluster 1
Index 79: Belongs 23.85% to cluster 1
Index 80: Belongs 5.06% to cluster 1
Index 81: Belongs 71.68% to cluster 1
Index 82: Belongs 10.70% to cluster 1
Index 83: Belongs 74.59% to cluster 1
Index 84: Belongs 74.35% to cluster 1
Index 85: Belongs 39.70% to cluster 1
Index 86: Belongs 23.70% to cluster 1
Index 87: Belongs 88.86% to cluster 1
Index 88: Belongs 93.00% to cluster 1
Index 89: Belongs 23.85% to cluster 1
Index 90: Belongs 5.06% to cluster 1
Index 91: Belongs 71.68% to cluster 1
Index 92: Belongs 10.70% to cluster 1
Index 93: Belongs 74.59% to cluster 1
Index 94: Belongs 74.35% to cluster 1
Index 95: Belongs 39.70% to cluster 1
Index 96: Belongs 23.70% to cluster 1
Index 97: Belongs 88.86% to cluster 1
Index 98: Belongs 93.00% to cluster 1
Index 99: Belongs 23.85% to cluster 1
Index 100: Belongs 5.06% to cluster 1
Index 101: Belongs 71.68% to cluster 1
Index 102: Belongs 10.70% to cluster 1
Index 103: Belongs 74.59% to cluster 1
Index 104: Belongs 74.35% to cluster 1
Index 105: Belongs 39.70% to cluster 1
Index 106: Belongs 23.70% to cluster 1
Index 107: Belongs 88.86% to cluster 1
Index 108: Belongs 93.00% to cluster 1
Index 109: Belongs 23.85% to cluster 1
Index 110: Belongs 5.06% to cluster 1
Index 111: Belongs 71.68% to cluster 1
Index 112: Belongs 10.70% to cluster 1
Index 113: Belongs 74.59% to cluster 1
Index 114: Belongs 74.35% to cluster 1
Index 115: Belongs 39.70% to cluster 1
Index 116: Belongs 23.70% to cluster 1
Index 117: Belongs 88.86% to cluster 1
Index 118: Belongs 93.00% to cluster 1
Index 119: Belongs 23.85% to cluster 1
Index 120: Belongs 5.06% to cluster 1
Index 121: Belongs 71.68% to cluster 1
Index 122: Belongs 10.70% to cluster 1
Index 123: Belongs 74.59% to cluster 1
Index 124: Belongs 74.35% to cluster 1
Index 125: Belongs 39.70% to cluster 1
Index 126: Belongs 23.70% to cluster 1
Index 127: Belongs 88.86% to cluster 1
Index 128: Belongs 93.00% to cluster 1
Index 129: Belongs 23.85% to cluster 1
Index 130: Belongs 5.06% to cluster 1
Index 131: Belongs 71.68% to cluster 1
Index 132: Belongs 10.70% to cluster 1
Index 133: Belongs 74.59% to cluster 1
Index 134: Belongs 74.35% to cluster 1
Index 135: Belongs 39.70% to cluster 1
Index 136: Belongs 23.70% to cluster 1
Index 137: Belongs 88.86% to cluster 1
Index 138: Belongs 93.00% to cluster 1
Index 139: Belongs 23.85% to cluster 1
Index 140: Belongs 5.06% to cluster 1
Index 141: Belongs 71.68% to cluster 1
Index 142: Belongs 10.70% to cluster 1
Index 143: Belongs 74.59% to cluster 1
Index 144: Belongs 74.35% to cluster 1
Index 145: Belongs 39.70% to cluster 1
Index 146: Belongs 23.70% to cluster 1
Index 147: Belongs 88.86% to cluster 1
Index 148: Belongs 93.00% to cluster 1
Index 149: Belongs 23.85% to cluster 1
Index 150: Belongs 5.06% to cluster 1
Index 151: Belongs 71.68% to cluster 1

Silhouette Score for 2 clusters: 0.6431

In [14]:
df_3 = pd.read_csv("mid_1.csv")
df_3.describe()

          load_ind   speed_ind  tyre_age_yrs  total_life_km
count   152.000000  152.000000    152.000000     152.000000
mean    498.289474   98.750000      3.197368   64111.842105
std     200.689627   19.910811      1.255660   21823.054017
min     272.000000   80.000000      1.000000   28000.000000
25%     335.000000   80.000000      2.000000   47000.000000
50%     468.500000   90.000000      3.000000   65000.000000
75%     600.000000  110.000000      4.000000   80000.000000
max    1030.000000  150.000000      5.000000  102000.000000

In [15]:
spd_ind_adj = []
for i in range(0,len(df_3)):
    spd_ind_adj.append(150 - df_3.speed_ind[i])
print(spd_ind_adj)

[60, 10, 40, 70, 60, 10, 40, 70, 70, 30, 60, 50, 70, 70, 0, 60, 10, 40, 70, 70, 30, 60, 50, 70, 70, 0, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40, 70, 20, 70, 50, 60, 20, 50, 70, 70, 40]

In [16]:
df_3["spd_ind_adj"] = spd_ind_adj
df_3.drop(columns = ["speed_ind"],inplace = True)

In [17]:
df_3.describe()

          load_ind  tyre_age_yrs  total_life_km  spd_ind_adj
count   152.000000    152.000000     152.000000   152.000000
mean    498.289474      3.197368   64111.842105    51.250000
std     200.689627      1.255660   21823.054017    19.910811
min     272.000000      1.000000   28000.000000     0.000000
25%     335.000000      2.000000   47000.000000    40.000000
50%     468.500000      3.000000   65000.000000    60.000000
75%     600.000000      4.000000   80000.000000    70.000000
max    1030.000000      5.000000  102000.000000    70.000000

In [18]:
df_3.to_csv("mid_2.csv",index = False)

In [27]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Step 1: Load the data from the CSV file
data = pd.read_csv("mid_2.csv")

# Step 2: Prepare the data for clustering
X = data.values  # Convert DataFrame to a NumPy array for clustering

# Step 3: Create and fit the KMeans model with 2 clusters
num_clusters = 3
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
kmeans.fit(X)

# Step 4: Get the cluster assignments and cluster centers
cluster_labels = kmeans.labels_
cluster_centers = kmeans.cluster_centers_

# Step 5: Print the indexes belonging to each cluster and their percentage of belongingness to cluster 1
for i, cluster_label in enumerate(cluster_labels):
    cluster_center_1 = cluster_centers[0]  # Center of cluster 1
    cluster_center_2 = cluster_centers[1]  # Center of cluster 2
    distance_to_cluster_1 = np.linalg.norm(X[i] - cluster_center_1)  # Distance to cluster 1 center
    distance_to_cluster_2 = np.linalg.norm(X[i] - cluster_center_2)  # Distance to cluster 2 center
    percentage_cluster_1 = distance_to_cluster_1 / (distance_to_cluster_1 + distance_to_cluster_2) * 100
    print(f"Index {i}: Belongs {percentage_cluster_1:.2f}% to cluster 1")

# Step 6: Calculate and print the silhouette score for 2 clusters
silhouette_avg = silhouette_score(X, cluster_labels)
print(f"\nSilhouette Score for 3 clusters: {silhouette_avg:.4f}")

Index 0: Belongs 67.16% to cluster 1
Index 1: Belongs 18.26% to cluster 1
Index 2: Belongs 1.31% to cluster 1
Index 3: Belongs 82.81% to cluster 1
Index 4: Belongs 67.16% to cluster 1
Index 5: Belongs 18.26% to cluster 1
Index 6: Belongs 1.31% to cluster 1
Index 7: Belongs 82.81% to cluster 1
Index 8: Belongs 85.73% to cluster 1
Index 9: Belongs 45.64% to cluster 1
Index 10: Belongs 47.60% to cluster 1
Index 11: Belongs 6.28% to cluster 1
Index 12: Belongs 96.50% to cluster 1
Index 13: Belongs 90.22% to cluster 1
Index 14: Belongs 4.74% to cluster 1
Index 15: Belongs 67.16% to cluster 1
Index 16: Belongs 18.26% to cluster 1
Index 17: Belongs 1.31% to cluster 1
Index 18: Belongs 82.81% to cluster 1
Index 19: Belongs 85.73% to cluster 1
Index 20: Belongs 45.64% to cluster 1
Index 21: Belongs 47.60% to cluster 1
Index 22: Belongs 6.28% to cluster 1
Index 23: Belongs 96.50% to cluster 1
Index 24: Belongs 90.22% to cluster 1
Index 25: Belongs 4.74% to cluster 1
Index 26: Belongs 69.12% to cluster 1
Index 27: Belongs 2.61% to cluster 1
Index 28: Belongs 18.26% to cluster 1
Index 29: Belongs 85.73% to cluster 1
Index 30: Belongs 82.81% to cluster 1
Index 31: Belongs 33.91% to cluster 1
Index 32: Belongs 96.50% to cluster 1
Index 33: Belongs 16.57% to cluster 1
Index 34: Belongs 31.95% to cluster 1
Index 35: Belongs 57.38% to cluster 1
Index 36: Belongs 69.12% to cluster 1
Index 37: Belongs 2.61% to cluster 1
Index 38: Belongs 18.26% to cluster 1
Index 39: Belongs 85.73% to cluster 1
Index 40: Belongs 82.81% to cluster 1
Index 41: Belongs 33.91% to cluster 1
Index 42: Belongs 96.50% to cluster 1
Index 43: Belongs 16.57% to cluster 1
Index 44: Belongs 31.95% to cluster 1
Index 45: Belongs 57.38% to cluster 1
Index 46: Belongs 69.12% to cluster 1
Index 47: Belongs 2.61% to cluster 1
Index 48: Belongs 18.26% to cluster 1
Index 49: Belongs 85.73% to cluster 1
Index 50: Belongs 82.81% to cluster 1
Index 51: Belongs 33.91% to cluster 1
Index 52: Belongs 96.50% to cluster 1
Index 53: Belongs 16.57% to cluster 1
Index 54: Belongs 31.95% to cluster 1
Index 55: Belongs 57.38% to cluster 1
Index 56: Belongs 69.12% to cluster 1
Index 57: Belongs 2.61% to cluster 1
Index 58: Belongs 18.26% to cluster 1
Index 59: Belongs 85.73% to cluster 1
Index 60: Belongs 82.81% to cluster 1
Index 61: Belongs 33.91% to cluster 1
Index 62: Belongs 96.50% to cluster 1
Index 63: Belongs 16.57% to cluster 1
Index 64: Belongs 31.95% to cluster 1
Index 65: Belongs 57.38% to cluster 1
Index 66: Belongs 69.12% to cluster 1
Index 67: Belongs 2.61% to cluster 1
Index 68: Belongs 18.26% to cluster 1
Index 69: Belongs 85.73% to cluster 1
Index 70: Belongs 82.81% to cluster 1
Index 71: Belongs 33.91% to cluster 1
Index 72: Belongs 96.50% to cluster 1
Index 73: Belongs 16.57% to cluster 1
Index 74: Belongs 31.95% to cluster 1
Index 75: Belongs 57.38% to cluster 1
Index 76: Belongs 69.12% to cluster 1
Index 77: Belongs 2.61% to cluster 1
Index 78: Belongs 18.26% to cluster 1
Index 79: Belongs 85.73% to cluster 1
Index 80: Belongs 82.81% to cluster 1
Index 81: Belongs 33.91% to cluster 1
Index 82: Belongs 96.50% to cluster 1
Index 83: Belongs 16.57% to cluster 1
Index 84: Belongs 31.95% to cluster 1
Index 85: Belongs 57.38% to cluster 1
Index 86: Belongs 69.12% to cluster 1
Index 87: Belongs 2.61% to cluster 1
Index 88: Belongs 18.26% to cluster 1
Index 89: Belongs 85.73% to cluster 1
Index 90: Belongs 82.81% to cluster 1
Index 91: Belongs 33.91% to cluster 1
Index 92: Belongs 96.50% to cluster 1
Index 93: Belongs 16.57% to cluster 1
Index 94: Belongs 31.95% to cluster 1
Index 95: Belongs 57.38% to cluster 1
Index 96: Belongs 69.12% to cluster 1
Index 97: Belongs 2.61% to cluster 1
Index 98: Belongs 18.26% to cluster 1
Index 99: Belongs 85.73% to cluster 1
Index 100: Belongs 82.81% to cluster 1
Index 101: Belongs 33.91% to cluster 1
Index 102: Belongs 96.50% to cluster 1
Index 103: Belongs 16.57% to cluster 1
Index 104: Belongs 31.95% to cluster 1
Index 105: Belongs 57.38% to cluster 1
Index 106: Belongs 69.12% to cluster 1
Index 107: Belongs 2.61% to cluster 1
Index 108: Belongs 18.26% to cluster 1
Index 109: Belongs 85.73% to cluster 1
Index 110: Belongs 82.81% to cluster 1
Index 111: Belongs 33.91% to cluster 1
Index 112: Belongs 96.50% to cluster 1
Index 113: Belongs 16.57% to cluster 1
Index 114: Belongs 31.95% to cluster 1
Index 115: Belongs 57.38% to cluster 1
Index 116: Belongs 69.12% to cluster 1
Index 117: Belongs 2.61% to cluster 1
Index 118: Belongs 18.26% to cluster 1
Index 119: Belongs 85.73% to cluster 1
Index 120: Belongs 82.81% to cluster 1
Index 121: Belongs 33.91% to cluster 1
Index 122: Belongs 96.50% to cluster 1
Index 123: Belongs 16.57% to cluster 1
Index 124: Belongs 31.95% to cluster 1
Index 125: Belongs 57.38% to cluster 1
Index 126: Belongs 69.12% to cluster 1
Index 127: Belongs 2.61% to cluster 1
Index 128: Belongs 18.26% to cluster 1
Index 129: Belongs 85.73% to cluster 1
Index 130: Belongs 82.81% to cluster 1
Index 131: Belongs 33.91% to cluster 1
Index 132: Belongs 96.50% to cluster 1
Index 133: Belongs 16.57% to cluster 1
Index 134: Belongs 31.95% to cluster 1
Index 135: Belongs 57.38% to cluster 1
Index 136: Belongs 69.12% to cluster 1
Index 137: Belongs 2.61% to cluster 1
Index 138: Belongs 18.26% to cluster 1
Index 139: Belongs 85.73% to cluster 1
Index 140: Belongs 82.81% to cluster 1
Index 141: Belongs 33.91% to cluster 1
Index 142: Belongs 96.50% to cluster 1
Index 143: Belongs 16.57% to cluster 1
Index 144: Belongs 31.95% to cluster 1
Index 145: Belongs 57.38% to cluster 1
Index 146: Belongs 69.12% to cluster 1
Index 147: Belongs 2.61% to cluster 1
Index 148: Belongs 18.26% to cluster 1
Index 149: Belongs 85.73% to cluster 1
Index 150: Belongs 82.81% to cluster 1
Index 151: Belongs 33.91% to cluster 1

Silhouette Score for 2 clusters: 0.5709

In [23]:
df_3.total_life_km[33]

102000.0

In [24]:
df_3.tyre_age_yrs[33]

4

In [26]:
(df_3.total_life_km[33]/102000 + df_3.tyre_age_yrs[33]/5 + df_3.spd_ind_adj[33]/70 + df_3.load_ind[33]/1030)/4

0.7714285714285715

In [28]:
# K - means clustering 
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Step 1: Load the data from the CSV file
data = pd.read_csv("mid_2.csv")

# Step 2: Prepare the data for clustering
X = data.values  # Convert DataFrame to a NumPy array for clustering

# Step 3: Create and fit the KMeans model with 2 clusters
num_clusters = 3
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
kmeans.fit(X)

# Step 4: Get the cluster assignments
cluster_labels = kmeans.labels_

# Step 5: Print the indexes belonging to each cluster
for cluster_num in range(num_clusters):
    cluster_indices = np.where(cluster_labels == cluster_num)[0]
    print(f"Data points in cluster {cluster_num}: {cluster_indices}")

# Step 6: Calculate and print the silhouette score for 2 clusters
silhouette_avg = silhouette_score(X, cluster_labels)
print(f"Silhouette Score for 3 clusters: {silhouette_avg:.4f}")

Data points in cluster 0: [  1   2   5   6  11  14  16  17  22  25  27  28  33  37  38  43  47  48
  53  57  58  63  67  68  73  77  78  83  87  88  93  97  98 103 107 108
 113 117 118 123 127 128 133 137 138 143 147 148]
Data points in cluster 1: [  3   7   8  12  13  18  19  23  24  29  30  32  39  40  42  49  50  52
  59  60  62  69  70  72  79  80  82  89  90  92  99 100 102 109 110 112
 119 120 122 129 130 132 139 140 142 149 150]
Data points in cluster 2: [  0   4   9  10  15  20  21  26  31  34  35  36  41  44  45  46  51  54
  55  56  61  64  65  66  71  74  75  76  81  84  85  86  91  94  95  96
 101 104 105 106 111 114 115 116 121 124 125 126 131 134 135 136 141 144
 145 146 151]
Silhouette Score for 3 clusters: 0.5709

In [29]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

def read_csv_data(file_path):
    return pd.read_csv(file_path)

def k_means_clustering(data, num_clusters=3):
    kmeans = KMeans(n_clusters=num_clusters)
    kmeans.fit(data)
    cluster_labels = kmeans.labels_
    centroids = kmeans.cluster_centers_
    return cluster_labels, centroids

def calculate_belongs_to_each_cluster(data, cluster_labels, num_clusters=3):
    belongs_to_clusters = np.zeros((len(data), num_clusters))
    for i, label in enumerate(cluster_labels):
        belongs_to_clusters[i, label] = 1
    return belongs_to_clusters

def print_belongs_to_each_cluster(belongs_to_clusters):
    print("Percentage of Belongingness to Each Cluster:")
    for idx, belongs_to_cluster in enumerate(belongs_to_clusters):
        percentages = belongs_to_cluster * 100
        print(f"Index {idx}: Cluster 0: {percentages[0]:.2f}%, Cluster 1: {percentages[1]:.2f}%, Cluster 2: {percentages[2]:.2f}%")

def calculate_silhouette_score(data, cluster_labels):
    return silhouette_score(data, cluster_labels)

if __name__ == "__main__":
    # Replace 'data.csv' with the actual file path of your CSV file
    file_path = "mid_2.csv"

    # Read data from CSV
    data = read_csv_data(file_path)

    # Perform K-means clustering
    cluster_labels, centroids = k_means_clustering(data)

    # Calculate percentage of belongingness to each cluster
    belongs_to_clusters = calculate_belongs_to_each_cluster(data, cluster_labels)

    # Print percentage of belongingness to each cluster for each index
    print_belongs_to_each_cluster(belongs_to_clusters)

    # Calculate and print the silhouette score
    silhouette_score_val = calculate_silhouette_score(data, cluster_labels)
    print(f"Silhouette Score: {silhouette_score_val:.4f}")

Percentage of Belongingness to Each Cluster:
Index 0: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 1: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 2: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 3: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 4: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 5: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 6: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 7: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 8: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 9: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 10: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 11: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 12: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 13: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 14: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 15: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 16: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 17: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 18: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 19: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 20: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 21: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 22: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 23: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 24: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 25: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 26: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 27: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 28: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 29: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 30: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 31: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 32: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 33: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 34: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 35: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 36: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 37: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 38: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 39: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 40: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 41: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 42: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 43: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 44: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 45: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 46: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 47: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 48: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 49: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 50: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 51: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 52: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 53: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 54: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 55: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 56: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 57: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 58: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 59: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 60: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 61: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 62: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 63: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 64: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 65: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 66: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 67: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 68: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 69: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 70: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 71: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 72: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 73: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 74: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 75: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 76: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 77: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 78: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 79: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 80: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 81: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 82: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 83: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 84: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 85: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 86: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 87: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 88: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 89: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 90: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 91: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 92: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 93: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 94: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 95: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 96: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 97: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 98: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 99: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 100: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 101: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 102: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 103: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 104: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 105: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 106: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 107: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 108: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 109: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 110: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 111: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 112: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 113: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 114: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 115: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 116: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 117: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 118: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 119: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 120: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 121: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 122: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 123: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 124: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 125: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 126: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 127: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 128: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 129: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 130: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 131: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 132: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 133: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 134: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 135: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 136: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 137: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 138: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 139: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 140: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 141: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 142: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 143: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 144: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 145: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 146: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Index 147: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 148: Cluster 0: 100.00%, Cluster 1: 0.00%, Cluster 2: 0.00%
Index 149: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 150: Cluster 0: 0.00%, Cluster 1: 100.00%, Cluster 2: 0.00%
Index 151: Cluster 0: 0.00%, Cluster 1: 0.00%, Cluster 2: 100.00%
Silhouette Score: 0.5709

In [59]:
df = pd.read_csv("tyre_hardness_percentage.csv")

In [60]:
df.describe()

       tyre_load_ind   total_life_km   no_of_yrs   percentage_hardness
count     316.000000      316.000000  316.000000            316.000000
mean       82.841772    61012.658228    5.518987             70.234177
std         5.949547    11222.985112    0.903057              3.645685
min        71.000000    40000.000000    4.000000             64.000000
25%        78.000000    50000.000000    5.000000             68.000000
50%        83.000000    60000.000000    5.000000             70.000000
75%        87.000000    70000.000000    6.000000             73.000000
max        95.000000    80000.000000    7.000000             78.000000

In [61]:
print(df)

     tyre_load_ind  tyre_speed_rating   total_life_km   no_of_yrs  \
0               85                  H           50000           5
1               95                  V           80000           7
2               72                  T           40000           4
3               91                  W           70000           6
4               80                  S           55000           5
..             ...                ...             ...         ...
311             82                  H           60000           5
312             90                  T           70000           6
313             78                  V           50000           5
314             86                  S           60000           5
315             83                  H           65000           6

      percentage_hardness
0                      70
1                      65
2                      75
3                      68
4                      72
..                    ...
311                    70
312                    68
313                    74
314                    70
315                    68

[316 rows x 5 columns]



# Assuming you have a DataFrame named 'df' with original column names
# For example, let's say you want to rename the column 'old_column_name' to 'new_column_name'

# Method 1: Using rename() method with a dictionary
#df.rename(columns={'old_column_name': 'new_column_name'}, inplace=True)

# Method 2: Using the columns attribute
# This method can be used if you want to rename multiple columns at once
# Create a dictionary with old column names as keys and new column names as values
# Then assign the updated column names back to the DataFrame
new_column_names = {
    'Tyre Load Index': 'tyre_load_index',
    'Total Life (km)': 'total_life_km',
    'No. of Years': 'no_of_yrs',
    'Percentage Hardness':'percentage_hardness'
}
df.columns = df.columns.map(new_column_names)

# Method 3: Using the rename() method with index argument
# This method allows you to rename the columns using the index position instead of the actual names
# For example, if the column you want to rename is the first column (index 0), you can do it like this:
df.rename(columns={df.columns[0]: 'new_column_name'}, inplace=True)

# Note: The inplace=True argument modifies the DataFrame in-place without creating a new copy. 
# If you don't want to modify the original DataFrame, you can omit inplace=True or set it to False.

In [63]:
tyre_ld_ind = []
ld_per_tyre_kg = [265,272,280,290,300,307,315,325,335,345,355,365,375,387,400,412,425,437,450,462,475,487,500,515,530,545,560,580,600,615,630,650,670,690,710,730,750,775,800,825,850,875,900,925,950,975,1000,1030,1060,1090,1120,1150,1180,1215,1250,1285,1320,1360,1400,1450,1500,1550,1600,1650,1700]
for i in range(62,127):
    tyre_ld_ind.append(i)
ld_per_tyre_kg_adj = []
#print(len(ld_per_tyre_kg) == len(tyre_ld_ind))
for i in df.tyre_load_ind:
    ld_per_tyre_kg_adj.append(ld_per_tyre_kg[tyre_ld_ind.index(i)])
print(len(ld_per_tyre_kg_adj))

316

In [65]:
df.drop(columns = ["tyre_load_ind"],inplace = True)
df.describe()

        total_life_km   no_of_yrs   percentage_hardness
count      316.000000  316.000000            316.000000
mean     61012.658228    5.518987             70.234177
std      11222.985112    0.903057              3.645685
min      40000.000000    4.000000             64.000000
25%      50000.000000    5.000000             68.000000
50%      60000.000000    5.000000             70.000000
75%      70000.000000    6.000000             73.000000
max      80000.000000    7.000000             78.000000

In [66]:
df["tyre_load_ind"] = ld_per_tyre_kg_adj

In [70]:
print(df)

     tyre_speed_rating   total_life_km   no_of_yrs   percentage_hardness  \
0                    H           50000           5                    70
1                    V           80000           7                    65
2                    T           40000           4                    75
3                    W           70000           6                    68
4                    S           55000           5                    72
..                 ...             ...         ...                   ...
311                  H           60000           5                    70
312                  T           70000           6                    68
313                  V           50000           5                    74
314                  S           60000           5                    70
315                  H           65000           6                    68

     tyre_load_ind
0              515
1              690
2              355
3              615
4              450
..             ...
311            475
312            600
313            425
314            530
315            487

[316 rows x 5 columns]

AttributeError: 'DataFrame' object has no attribute 'tyre_speed_rating'

In [72]:
df.tyre_speed_rating[0]

AttributeError: 'DataFrame' object has no attribute 'tyre_speed_rating'

In [73]:
columns_list = list(df.columns)
print(columns_list)

[' tyre_speed_rating', ' total_life_km', ' no_of_yrs', ' percentage_hardness', 'tyre_load_ind']

In [74]:
df.rename(columns={' tyre_speed_rating': 'tyre_speed_rating'}, inplace=True)

In [75]:
df.rename(columns={' total_life_km': 'total_life_km'}, inplace=True)

In [76]:
df.rename(columns={' no_of_yrs': 'no_of_yrs'}, inplace=True)

In [77]:
df.rename(columns={' percentage_hardness': 'percentage_hardness'}, inplace=True)

In [78]:
columns_list = list(df.columns)
print(columns_list)

['tyre_speed_rating', 'total_life_km', 'no_of_yrs', 'percentage_hardness', 'tyre_load_ind']

In [81]:
tyre_speed_rating = [' F',' G',' J',' K',' L',' M',' N',' P',' Q',' R',' S',' T',' U',' H',' V',' W',' Y',' (Y)']
tyre_speed_rat_kmph = [80,90,100,110,120,130,140,150,160,170,180,190,200,210,240,270,300,360]
tyre_sp_rat_adj = []
for i in df.tyre_speed_rating:
    #print(i)
    tyre_sp_rat_adj.append(tyre_speed_rat_kmph[tyre_speed_rating.index(i)])
for i in tyre_sp_rat_adj:
    print(type(i), i)

<class 'int'> 210
<class 'int'> 240
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 270
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210
<class 'int'> 190
<class 'int'> 270
<class 'int'> 210
<class 'int'> 190
<class 'int'> 240
<class 'int'> 180
<class 'int'> 210

In [82]:
df.drop(columns = ["tyre_speed_rating"],inplace = True)
df["tyre_speed_rat_kmph"] = tyre_sp_rat_adj
df.describe()

,total_life_km,no_of_yrs,percentage_hardness,tyre_load_ind,tyre_speed_rat_kmph
count,316.000000,316.000000,316.000000,316.000000,316.000000
mean,61012.658228,5.518987,70.234177,492.860759,213.607595
std,11222.985112,0.903057,3.645685,83.752695,31.294167
min,40000.000000,4.000000,64.000000,345.000000,180.000000
25%,50000.000000,5.000000,68.000000,425.000000,190.000000
50%,60000.000000,5.000000,70.000000,487.000000,210.000000
75%,70000.000000,6.000000,73.000000,545.000000,240.000000
max,80000.000000,7.000000,78.000000,690.000000,270.000000

In [83]:
p_h = []
for i in df.percentage_hardness:
    p_h.append(i)
df.drop(columns = ["percentage_hardness"],inplace = True)
df["percent_hardness"] = p_h
df.describe()

,total_life_km,no_of_yrs,tyre_load_ind,tyre_speed_rat_kmph,percent_hardness
count,316.000000,316.000000,316.000000,316.000000,316.000000
mean,61012.658228,5.518987,492.860759,213.607595,70.234177
std,11222.985112,0.903057,83.752695,31.294167,3.645685
min,40000.000000,4.000000,345.000000,180.000000,64.000000
25%,50000.000000,5.000000,425.000000,190.000000,68.000000
50%,60000.000000,5.000000,487.000000,210.000000,70.000000
75%,70000.000000,6.000000,545.000000,240.000000,73.000000
max,80000.000000,7.000000,690.000000,270.000000,78.000000

In [84]:
df.to_csv("percent_hard.csv",index = False)

In [85]:
# GRADIENT BOOSTING MACHINE - REGRESSION
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Step 1: Read the data from the CSV file
def read_data(filename):
    data = pd.read_csv(filename)
    return data

# Step 2: Split the data into features (X) and target (y)
def split_data(data):
    X = data.iloc[:, :-1]
    y = data.iloc[:, -1]
    return X, y

# Step 3: Split the data into training and testing sets
def split_train_test(X, y, test_size=0.2, random_state=42):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
    return X_train, X_test, y_train, y_test

# Step 4: Create and train the Gradient Boosting Machine Regression model
def train_gradient_boosting_regression(X_train, y_train):
    model = GradientBoostingRegressor()
    model.fit(X_train, y_train)
    return model

# Step 5: Make predictions using the trained model
def make_predictions(model, X_test):
    y_pred = model.predict(X_test)
    return y_pred

# Step 6: Evaluate the model's performance
def evaluate_model(y_test, y_pred):
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return mse, r2

if __name__ == "__main__":
    # Step 1: Read the data from the CSV file
    data = read_data("percent_hard.csv")

    # Step 2: Split the data into features (X) and target (y)
    X, y = split_data(data)

    # Step 3: Split the data into training and testing sets
    X_train, X_test, y_train, y_test = split_train_test(X, y)

    # Step 4: Create and train the Gradient Boosting Machine Regression model
    model = train_gradient_boosting_regression(X_train, y_train)

    # Step 5: Make predictions using the trained model
    y_pred = make_predictions(model, X_test)

    # Step 6: Evaluate the model's performance
    mse, r2 = evaluate_model(y_test, y_pred)

    print("Mean Squared Error:", mse)
    print("R-squared:", r2)

Mean Squared Error: 0.0482647765631353
R-squared: 0.9957448875419156

In [87]:
df_1 = pd.read_csv("final28.csv")
df_1.describe()

,tire_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000

In [88]:
import pandas as pd
import pickle

# Load the trained model from the file (change 'model_file.pkl' to the actual file path)
model_filename = 'model_file_percent_hard.pkl'
with open(model_filename, 'rb') as file:
    model = pickle.load(file)

# Load the input data from the separate CSV file
input_data = pd.read_csv("final28.csv")

# Assuming the two input variables are in columns 'variable1' and 'variable2'
# Extract the input variables from the input data
variable1_values = input_data['total_life_km']
variable2_values = input_data['tyre_age_yrs']
variable3_values = input_data['load_ind']
variable4_values = input_data['speed_ind']


# Create a list of input pairs for prediction
input_vars = list(zip(variable1_values, variable2_values, variable3_values, variable4_values))

# Make predictions
predicted_output = model.predict(input_vars)

# Print the predicted output
print("Predicted target variables:", predicted_output)

Predicted target variables: [75.84640267 66.48188618 67.59718434 70.44083296 75.84640267 66.48188618
 67.59718434 70.44083296 76.9002088  71.80826038 73.62891107 67.79449439
 76.51329743 76.9002088  66.01401663 75.84640267 66.48188618 67.59718434
 70.44083296 76.9002088  71.80826038 73.62891107 67.79449439 76.51329743
 76.9002088  66.01401663 75.84640267 66.23652749 67.63239383 76.9002088
 70.44083296 74.31671701 76.9002088  66.24247962 70.99759449 69.60993106
 75.84640267 66.23652749 67.63239383 76.9002088  70.44083296 74.31671701
 76.9002088  66.24247962 70.99759449 69.60993106 75.84640267 66.23652749
 67.63239383 76.9002088  70.44083296 74.31671701 76.9002088  66.24247962
 70.99759449 69.60993106 75.84640267 66.23652749 67.63239383 76.9002088
 70.44083296 74.31671701 76.9002088  66.24247962 70.99759449 69.60993106
 75.84640267 66.23652749 67.63239383 76.9002088  70.44083296 74.31671701
 76.9002088  66.24247962 70.99759449 69.60993106 75.84640267 66.23652749
 67.63239383 76.9002088  70.44083296 74.31671701 76.9002088  66.24247962
 70.99759449 69.60993106 75.84640267 66.23652749 67.63239383 76.9002088
 70.44083296 74.31671701 76.9002088  66.24247962 70.99759449 69.60993106
 75.84640267 66.23652749 67.63239383 76.9002088  70.44083296 74.31671701
 76.9002088  66.24247962 70.99759449 69.60993106 75.84640267 66.23652749
 67.63239383 76.9002088  70.44083296 74.31671701 76.9002088  66.24247962
 70.99759449 69.60993106 75.84640267 66.23652749 67.63239383 76.9002088
 70.44083296 74.31671701 76.9002088  66.24247962 70.99759449 69.60993106
 75.84640267 66.23652749 67.63239383 76.9002088  70.44083296 74.31671701
 76.9002088  66.24247962 70.99759449 69.60993106 75.84640267 66.23652749
 67.63239383 76.9002088  70.44083296 74.31671701 76.9002088  66.24247962
 70.99759449 69.60993106 75.84640267 66.23652749 67.63239383 76.9002088
 70.44083296 74.31671701]

In [90]:
def round_to_two_decimal_places(number):
    rounded_number = round(number, 2)
    return rounded_number

In [91]:
pred_out = list(predicted_output)
prctg_hard = []
for i in pred_out:
    prctg_hard.append(round_to_two_decimal_places(i))
print(prctg_hard)

[75.85, 66.48, 67.6, 70.44, 75.85, 66.48, 67.6, 70.44, 76.9, 71.81, 73.63, 67.79, 76.51, 76.9, 66.01, 75.85, 66.48, 67.6, 70.44, 76.9, 71.81, 73.63, 67.79, 76.51, 76.9, 66.01, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32, 76.9, 66.24, 71.0, 69.61, 75.85, 66.24, 67.63, 76.9, 70.44, 74.32]

In [92]:
df_1["percent_hardness"] = prctg_hard
df_1.describe()

,tire_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,percent_hardness
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,71.533882
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,4.044737
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,66.010000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,67.630000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,70.720000
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,75.850000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,76.900000

In [95]:
df_2 = pd.read_csv("final.csv")

In [96]:
df_2.describe()

,temperature_celsius,tire_pressure_psi,tire_age_years,vehicle_load_kg,vehicle_speed_kmh,mileage_km,tire_depth_mm,tire_width_mm,remaining_distance_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,26.217105,31.835526,3.197368,1677.631579,63.322368,45631.578947,6.030921,212.631579,18480.263158
std,2.646797,2.680427,1.255660,200.726287,15.525498,14272.041956,0.525538,17.443830,7804.711088
min,22.000000,27.000000,1.000000,1400.000000,40.000000,20000.000000,5.200000,185.000000,7000.000000
25%,24.000000,30.000000,2.000000,1500.000000,50.000000,35000.000000,5.700000,195.000000,12000.000000
50%,26.000000,32.000000,3.000000,1600.000000,65.000000,45000.000000,6.000000,205.000000,18000.000000
75%,28.000000,34.000000,4.000000,1800.000000,75.000000,55000.000000,6.400000,225.000000,25000.000000
max,32.000000,37.000000,5.000000,2000.000000,100.000000,70000.000000,7.200000,235.000000,32000.000000

In [99]:
mileage_km= []
rem_dist_km = []
for i in range(0,152):
    mileage_km.append(df_2.mileage_km[i])
    rem_dist_km.append(df_2.remaining_distance_km[i])
df_1["mileage_km"] = mileage_km
df_1["rem_dist_km"] = rem_dist_km
df_1.describe()

,tire_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,percent_hardness,mileage_km,rem_dist_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,71.533882,45631.578947,18480.263158
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,4.044737,14272.041956,7804.711088
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,66.010000,20000.000000,7000.000000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,67.630000,35000.000000,12000.000000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,70.720000,45000.000000,18000.000000
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,75.850000,55000.000000,25000.000000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,76.900000,70000.000000,32000.000000

In [100]:
df.rename(columns={'tire_pressure_psi': 'tyre_press_psi'}, inplace=True)

In [101]:
df_1.describe()

,tire_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,percent_hardness,mileage_km,rem_dist_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,71.533882,45631.578947,18480.263158
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,4.044737,14272.041956,7804.711088
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,66.010000,20000.000000,7000.000000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,67.630000,35000.000000,12000.000000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,70.720000,45000.000000,18000.000000
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,75.850000,55000.000000,25000.000000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,76.900000,70000.000000,32000.000000

In [102]:
df_1.to_csv("final31.csv",index = False)

In [104]:
run_per_yr = []
for i in range(0,152):
    run_per_yr.append(df_1.mileage_km[i]/df_1.tyre_age_yrs[i])
print(run_per_yr)

[20000.0, 13750.0, 20000.0, 7000.0, 20000.0, 13750.0, 20000.0, 7000.0, 20000.0, 12000.0, 22500.0, 21666.666666666668, 7500.0, 12500.0, 12000.0, 20000.0, 13750.0, 20000.0, 7000.0, 20000.0, 12000.0, 22500.0, 21666.666666666668, 7500.0, 12500.0, 12000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668, 15000.0, 17500.0, 18333.333333333332, 9000.0, 20000.0, 15000.0, 18333.333333333332, 20000.0, 7000.0, 16666.666666666668]

In [105]:
df_1["run_per_yr_km"] = run_per_yr

In [106]:
df_1.describe()

,tire_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,percent_hardness,mileage_km,rem_dist_km,run_per_yr_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,71.533882,45631.578947,18480.263158,15641.995614
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,4.044737,14272.041956,7804.711088,4456.795693
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,66.010000,20000.000000,7000.000000,7000.000000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,67.630000,35000.000000,12000.000000,13750.000000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,70.720000,45000.000000,18000.000000,16666.666667
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,75.850000,55000.000000,25000.000000,18750.000000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,76.900000,70000.000000,32000.000000,22500.000000

In [107]:
prctg_hard = []
run_per_yr_km = []
for i in range(0,152):
    prctg_hard.append(df_1.percent_hardness[i])
    run_per_yr_km.append(df_1.run_per_yr_km[i])

In [108]:
df_1.drop(columns = ["percent_hardness"],inplace = True)
df_1.describe()

,tire_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,mileage_km,rem_dist_km,run_per_yr_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,45631.578947,18480.263158,15641.995614
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,14272.041956,7804.711088,4456.795693
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,20000.000000,7000.000000,7000.000000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,35000.000000,12000.000000,13750.000000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,45000.000000,18000.000000,16666.666667
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,55000.000000,25000.000000,18750.000000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,70000.000000,32000.000000,22500.000000

In [111]:
df_1.rename(columns = {"tire_pressure_psi":"tyre_pressure_psi"},inplace = True)

In [112]:
df_1.describe()

,tyre_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,mileage_km,rem_dist_km,run_per_yr_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,45631.578947,18480.263158,15641.995614
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,14272.041956,7804.711088,4456.795693
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,20000.000000,7000.000000,7000.000000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,35000.000000,12000.000000,13750.000000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,45000.000000,18000.000000,16666.666667
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,55000.000000,25000.000000,18750.000000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,70000.000000,32000.000000,22500.000000

In [113]:
df_1.to_csv("final32.csv",index = False)

In [22]:
# GRADIENT BOOSTING MACHINE - REGRESSION
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Step 1: Read the data from the CSV file
def read_data(filename):
    data = pd.read_csv(filename)
    return data

# Step 2: Split the data into features (X) and target (y)
def split_data(data):
    X = data.iloc[:, :-1]
    y = data.iloc[:, -1]
    return X, y

# Step 3: Split the data into training and testing sets
def split_train_test(X, y, test_size=0.2, random_state=42):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
    return X_train, X_test, y_train, y_test

# Step 4: Create and train the Gradient Boosting Machine Regression model
def train_gradient_boosting_regression(X_train, y_train):
    model = GradientBoostingRegressor()
    model.fit(X_train, y_train)
    return model

# Step 5: Make predictions using the trained model
def make_predictions(model, X_test):
    y_pred = model.predict(X_test)
    return y_pred

# Step 6: Evaluate the model's performance
def evaluate_model(y_test, y_pred):
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return mse, r2

if __name__ == "__main__":
    # Step 1: Read the data from the CSV file
    data = read_data("new_total_life_km.csv")

    # Step 2: Split the data into features (X) and target (y)
    X, y = split_data(data)

    # Step 3: Split the data into training and testing sets
    X_train, X_test, y_train, y_test = split_train_test(X, y)

    # Step 4: Create and train the Gradient Boosting Machine Regression model
    model = train_gradient_boosting_regression(X_train, y_train)

    # Step 5: Make predictions using the trained model
    y_pred = make_predictions(model, X_test)

    # Step 6: Evaluate the model's performance
    mse, r2 = evaluate_model(y_test, y_pred)

    print("Mean Squared Error:", mse)
    print("R-squared:", r2)

Mean Squared Error: 0.033747184502184606
R-squared: 0.9999999992904398

In [115]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Step 1: Read the data from the CSV file
def read_data(filename):
    data = pd.read_csv(filename)
    return data

# Step 2: Split the data into features (X) and target (y)
def split_data(data):
    X = data.iloc[:, :-1]
    y = data.iloc[:, -1]
    return X, y

# Step 3: Split the data into training and testing sets
def split_train_test(X, y, test_size=0.2, random_state=42):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)
    return X_train, X_test, y_train, y_test

# Step 4: Create and train the Random Forest Regression model
def train_random_forest_regression(X_train, y_train):
    model = RandomForestRegressor()
    model.fit(X_train, y_train)
    return model

# Step 5: Make predictions using the trained model
def make_predictions(model, X_test):
    y_pred = model.predict(X_test)
    return y_pred

# Step 6: Evaluate the model's performance
def evaluate_model(y_test, y_pred):
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return mse, r2

if __name__ == "__main__":
    # Step 1: Read the data from the CSV file
    data = read_data("new_1.csv")

    # Step 2: Split the data into features (X) and target (y)
    X, y = split_data(data)

    # Step 3: Split the data into training and testing sets
    X_train, X_test, y_train, y_test = split_train_test(X, y)

    # Step 4: Create and train the Random Forest Regression model
    model = train_random_forest_regression(X_train, y_train)

    # Step 5: Make predictions using the trained model
    y_pred = make_predictions(model, X_test)

    # Step 6: Evaluate the model's performance
    mse, r2 = evaluate_model(y_test, y_pred)

    print("Mean Squared Error:", mse)
    print("R-squared:", r2)

Mean Squared Error: 0.0
R-squared: 1.0

In [1]:
import pandas as pd

In [2]:
df_1 = pd.read_csv("new_1.csv")
df_1.describe()

,speed_rating_kmph,load_ind_kg,total_life_km,vehicle_speed_kmph,vehicle_weight_kg,tyre_pressure_psi,recomm_tyre_press_psi,tread_depth_mm_new,no_of_yrs
count,334.00000,334.000000,334.000000,334.00000,334.000000,334.000000,334.000000,334.000000,334.000000
mean,199.97006,598.907186,69970.059880,119.97006,1759.580838,34.000000,35.997006,9.697605,5.997006
std,14.17392,59.854080,7071.004235,14.17392,185.869770,1.418454,1.417392,1.079370,0.895429
min,180.00000,515.000000,60000.000000,100.00000,1500.000000,32.000000,34.000000,8.000000,5.000000
25%,190.00000,560.000000,65000.000000,110.00000,1600.000000,33.000000,35.000000,9.000000,5.000000
50%,200.00000,600.000000,70000.000000,120.00000,1800.000000,34.000000,36.000000,10.000000,6.000000
75%,210.00000,630.000000,75000.000000,130.00000,1900.000000,35.000000,37.000000,10.500000,7.000000
max,220.00000,690.000000,80000.000000,140.00000,2000.000000,36.000000,38.000000,11.000000,7.000000

In [3]:
no_of_yrs = []
for i in df_1.no_of_yrs:
    no_of_yrs.append(i)
print(len(no_of_yrs))

334

In [4]:
total_life_km = []
for i in df_1.total_life_km:
    total_life_km.append(i)
print(len(total_life_km))

334

In [5]:
df_1.drop(columns = ["total_life_km","no_of_yrs"],inplace = True)
df_1.describe()

,speed_rating_kmph,load_ind_kg,vehicle_speed_kmph,vehicle_weight_kg,tyre_pressure_psi,recomm_tyre_press_psi,tread_depth_mm_new
count,334.00000,334.000000,334.00000,334.000000,334.000000,334.000000,334.000000
mean,199.97006,598.907186,119.97006,1759.580838,34.000000,35.997006,9.697605
std,14.17392,59.854080,14.17392,185.869770,1.418454,1.417392,1.079370
min,180.00000,515.000000,100.00000,1500.000000,32.000000,34.000000,8.000000
25%,190.00000,560.000000,110.00000,1600.000000,33.000000,35.000000,9.000000
50%,200.00000,600.000000,120.00000,1800.000000,34.000000,36.000000,10.000000
75%,210.00000,630.000000,130.00000,1900.000000,35.000000,37.000000,10.500000
max,220.00000,690.000000,140.00000,2000.000000,36.000000,38.000000,11.000000

In [6]:
df_1["total_life_km"] = total_life_km
df_1.describe()

,speed_rating_kmph,load_ind_kg,vehicle_speed_kmph,vehicle_weight_kg,tyre_pressure_psi,recomm_tyre_press_psi,tread_depth_mm_new,total_life_km
count,334.00000,334.000000,334.00000,334.000000,334.000000,334.000000,334.000000,334.000000
mean,199.97006,598.907186,119.97006,1759.580838,34.000000,35.997006,9.697605,69970.059880
std,14.17392,59.854080,14.17392,185.869770,1.418454,1.417392,1.079370,7071.004235
min,180.00000,515.000000,100.00000,1500.000000,32.000000,34.000000,8.000000,60000.000000
25%,190.00000,560.000000,110.00000,1600.000000,33.000000,35.000000,9.000000,65000.000000
50%,200.00000,600.000000,120.00000,1800.000000,34.000000,36.000000,10.000000,70000.000000
75%,210.00000,630.000000,130.00000,1900.000000,35.000000,37.000000,10.500000,75000.000000
max,220.00000,690.000000,140.00000,2000.000000,36.000000,38.000000,11.000000,80000.000000

In [7]:
df_1.to_csv("new_total_life_km.csv",index = False)

In [9]:
df_1.drop(columns = ["total_life_km"],inplace = True)
df_1.describe()

,speed_rating_kmph,load_ind_kg,vehicle_speed_kmph,vehicle_weight_kg,tyre_pressure_psi,recomm_tyre_press_psi,tread_depth_mm_new
count,334.00000,334.000000,334.00000,334.000000,334.000000,334.000000,334.000000
mean,199.97006,598.907186,119.97006,1759.580838,34.000000,35.997006,9.697605
std,14.17392,59.854080,14.17392,185.869770,1.418454,1.417392,1.079370
min,180.00000,515.000000,100.00000,1500.000000,32.000000,34.000000,8.000000
25%,190.00000,560.000000,110.00000,1600.000000,33.000000,35.000000,9.000000
50%,200.00000,600.000000,120.00000,1800.000000,34.000000,36.000000,10.000000
75%,210.00000,630.000000,130.00000,1900.000000,35.000000,37.000000,10.500000
max,220.00000,690.000000,140.00000,2000.000000,36.000000,38.000000,11.000000

In [10]:
df_1["no_of_yrs"] = no_of_yrs
df_1.describe()

,speed_rating_kmph,load_ind_kg,vehicle_speed_kmph,vehicle_weight_kg,tyre_pressure_psi,recomm_tyre_press_psi,tread_depth_mm_new,no_of_yrs
count,334.00000,334.000000,334.00000,334.000000,334.000000,334.000000,334.000000,334.000000
mean,199.97006,598.907186,119.97006,1759.580838,34.000000,35.997006,9.697605,5.997006
std,14.17392,59.854080,14.17392,185.869770,1.418454,1.417392,1.079370,0.895429
min,180.00000,515.000000,100.00000,1500.000000,32.000000,34.000000,8.000000,5.000000
25%,190.00000,560.000000,110.00000,1600.000000,33.000000,35.000000,9.000000,5.000000
50%,200.00000,600.000000,120.00000,1800.000000,34.000000,36.000000,10.000000,6.000000
75%,210.00000,630.000000,130.00000,1900.000000,35.000000,37.000000,10.500000,7.000000
max,220.00000,690.000000,140.00000,2000.000000,36.000000,38.000000,11.000000,7.000000

In [11]:
df_1.to_csv("new_no_of_yrs",index = False)

In [12]:
df_1 = pd.read_csv("final32.csv")

In [13]:
df_1.describe()

,tyre_pressure_psi,vehicle_speed_kmh,tyre_sdwl_mm,load_per_tyre_kg,total_life_km,tyre_age_yrs,load_ind,speed_ind,tread_depth_mm,tyre_width_mm,recomm_tyre_press,mileage_km,rem_dist_km,run_per_yr_km
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,113.766447,419.407895,64111.842105,3.197368,498.289474,98.750000,6.030921,212.631579,33.131579,45631.578947,18480.263158,15641.995614
std,2.680427,15.525498,12.381714,50.181572,21823.054017,1.255660,200.689627,19.910811,0.525538,17.443830,2.382842,14272.041956,7804.711088,4456.795693
min,27.000000,40.000000,90.000000,350.000000,28000.000000,1.000000,272.000000,80.000000,5.200000,185.000000,30.000000,20000.000000,7000.000000,7000.000000
25%,30.000000,50.000000,101.250000,375.000000,47000.000000,2.000000,335.000000,80.000000,5.700000,195.000000,31.000000,35000.000000,12000.000000,13750.000000
50%,32.000000,65.000000,112.750000,400.000000,65000.000000,3.000000,468.500000,90.000000,6.000000,205.000000,35.000000,45000.000000,18000.000000,16666.666667
75%,34.000000,75.000000,126.750000,450.000000,80000.000000,4.000000,600.000000,110.000000,6.400000,225.000000,35.000000,55000.000000,25000.000000,18750.000000
max,37.000000,100.000000,129.250000,500.000000,102000.000000,5.000000,1030.000000,150.000000,7.200000,235.000000,36.000000,70000.000000,32000.000000,22500.000000

In [15]:
df_1.drop(columns = ["mileage_km","run_per_yr_km","tyre_age_yrs","tyre_width_mm","tyre_sdwl_mm","total_life_km","rem_dist_km"],inplace = True)
df_1.describe()

,tyre_pressure_psi,vehicle_speed_kmh,load_per_tyre_kg,load_ind,speed_ind,tread_depth_mm,recomm_tyre_press
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,31.835526,63.322368,419.407895,498.289474,98.750000,6.030921,33.131579
std,2.680427,15.525498,50.181572,200.689627,19.910811,0.525538,2.382842
min,27.000000,40.000000,350.000000,272.000000,80.000000,5.200000,30.000000
25%,30.000000,50.000000,375.000000,335.000000,80.000000,5.700000,31.000000
50%,32.000000,65.000000,400.000000,468.500000,90.000000,6.000000,35.000000
75%,34.000000,75.000000,450.000000,600.000000,110.000000,6.400000,35.000000
max,37.000000,100.000000,500.000000,1030.000000,150.000000,7.200000,36.000000

In [16]:
tp_psi = []
vs_kmh = []
vw_kg = []
ld_ind = []
td_mm = []
rtp_psi = []
for i in range(0,152):
    tp_psi.append(df_1.tyre_pressure_psi[i])
    vs_kmh.append(df_1.vehicle_speed_kmh[i])
    vw_kg.append(df_1.load_per_tyre_kg[i]*4)
    ld_ind.append(df_1.load_ind[i])
    td_mm.append(df_1.tread_depth_mm[i])
    rtp_psi.append(df_1.recomm_tyre_press[i])
df_1.drop(columns = ["tyre_pressure_psi","vehicle_speed_kmh","load_per_tyre_kg","load_ind","tread_depth_mm","recomm_tyre_press"],inplace = True)
df_1["load_ind_kg"] = ld_ind
df_1["vehicle_speed_kmph"] = vs_kmh
df_1["vehicle_weight_kg"] = vw_kg
df_1["tyre_pressure_psi"] = tp_psi
df_1["recomm_tyre_press_psi"] = rtp_psi
df_1["tread_depth_mm_new"] = td_mm

In [17]:
df_1.rename(columns = {"speed_ind":"speed_rating_kmph"},inplace = True)

In [19]:
df_1.describe()

,speed_rating_kmph,load_ind_kg,vehicle_speed_kmph,vehicle_weight_kg,tyre_pressure_psi,recomm_tyre_press_psi,tread_depth_mm_new
count,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000,152.000000
mean,98.750000,498.289474,63.322368,1677.631579,31.835526,33.131579,6.030921
std,19.910811,200.689627,15.525498,200.726287,2.680427,2.382842,0.525538
min,80.000000,272.000000,40.000000,1400.000000,27.000000,30.000000,5.200000
25%,80.000000,335.000000,50.000000,1500.000000,30.000000,31.000000,5.700000
50%,90.000000,468.500000,65.000000,1600.000000,32.000000,35.000000,6.000000
75%,110.000000,600.000000,75.000000,1800.000000,34.000000,35.000000,6.400000
max,150.000000,1030.000000,100.000000,2000.000000,37.000000,36.000000,7.200000

In [20]:
df_1.to_csv("final33.csv",index = False)

In [23]:
import pandas as pd
import pickle

# Load the trained model from the file (change 'model_file.pkl' to the actual file path)
model_filename = 'model_file_no_of_yrs.pkl'
with open(model_filename, 'rb') as file:
    model = pickle.load(file)

# Load the input data from the separate CSV file
input_data = pd.read_csv("final33.csv")

# Assuming the two input variables are in columns 'variable1' and 'variable2'
# Extract the input variables from the input data
variable1_values = input_data['speed_rating_kmph']
variable2_values = input_data['load_ind_kg']
variable3_values = input_data['vehicle_speed_kmph']
variable4_values = input_data['vehicle_weight_kg']
variable5_values = input_data['tyre_pressure_psi']
variable6_values = input_data['recomm_tyre_press_psi']
variable7_values = input_data['tread_depth_mm_new']



# Create a list of input pairs for prediction
input_vars = list(zip(variable1_values, variable2_values, variable3_values, variable4_values,variable5_values,variable6_values,variable7_values))

# Make predictions
predicted_output = model.predict(input_vars)

# Print the predicted output
print("Predicted target variables:", predicted_output)

Predicted target variables: [5.00002676 5.51557809 5.00002676 5.33504308 5.00002676 5.51557809
 5.00002676 5.33504308 5.00002676 5.00002676 5.00002676 5.32221903
 5.19338582 5.21954901 5.7021198  5.00002676 5.51557809 5.00002676
 5.33504308 5.00002676 5.00002676 5.00002676 5.32221903 5.19338582
 5.21954901 5.7021198  5.00002676 5.66315824 5.00002676 5.00002676
 5.33504308 5.00002676 5.00002676 5.84702713 5.00002676 5.55142817
 5.00002676 5.66315824 5.00002676 5.00002676 5.33504308 5.00002676
 5.21954901 5.84702713 5.00002676 5.55142817 5.00002676 5.84702713
 5.00002676 5.00002676 5.33504308 5.00002676 5.00002676 5.84702713
 5.00002676 5.55142817 5.00002676 5.66315824 5.00002676 5.00002676
 5.33504308 5.00002676 5.21954901 5.84702713 5.00002676 5.55142817
 5.00002676 5.66315824 5.00002676 5.00002676 5.33504308 5.00002676
 5.21954901 5.84702713 5.00002676 5.55142817 5.00002676 5.66315824
 5.00002676 5.00002676 5.33504308 5.00002676 5.21954901 5.84702713
 5.00002676 5.55142817 5.00002676 5.66315824 5.00002676 5.00002676
 5.33504308 5.00002676 5.21954901 5.84702713 5.00002676 5.55142817
 5.00002676 5.66315824 5.00002676 5.00002676 5.33504308 5.00002676
 5.21954901 5.84702713 5.00002676 5.55142817 5.00002676 5.66315824
 5.00002676 5.00002676 5.33504308 5.00002676 5.21954901 5.84702713
 5.00002676 5.55142817 5.00002676 5.66315824 5.00002676 5.00002676
 5.33504308 5.00002676 5.21954901 5.84702713 5.00002676 5.55142817
 5.00002676 5.66315824 5.00002676 5.00002676 5.33504308 5.00002676
 5.21954901 5.84702713 5.00002676 5.55142817 5.00002676 5.66315824
 5.00002676 5.00002676 5.33504308 5.00002676 5.21954901 5.84702713
 5.00002676 5.55142817 5.00002676 5.66315824 5.00002676 5.00002676
 5.33504308 5.00002676]

In [27]:
prd_out_no_of_yrs = []
for i in predicted_output:
    prd_out_no_of_yrs.append(round(i))
print(len(prd_out_no_of_yrs))
print(prd_out_no_of_yrs)

152
[5, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5]

In [1]:
import pandas as pd
import pickle

# Load the trained model from the file (change 'model_file.pkl' to the actual file path)
model_filename = 'model_file_total_life_km.pkl'
with open(model_filename, 'rb') as file:
    model = pickle.load(file)

# Load the input data from the separate CSV file
input_data = pd.read_csv("final33.csv")

# Assuming the two input variables are in columns 'variable1' and 'variable2'
# Extract the input variables from the input data
variable1_values = input_data['speed_rating_kmph']
variable2_values = input_data['load_ind_kg']
variable3_values = input_data['vehicle_speed_kmph']
variable4_values = input_data['vehicle_weight_kg']
variable5_values = input_data['tyre_pressure_psi']
variable6_values = input_data['recomm_tyre_press_psi']
variable7_values = input_data['tread_depth_mm_new']



# Create a list of input pairs for prediction
input_vars = list(zip(variable1_values, variable2_values, variable3_values, variable4_values,variable5_values,variable6_values,variable7_values))

# Make predictions
predicted_output = model.predict(input_vars)

# Print the predicted output
print("Predicted target variables:", predicted_output)

Predicted target variables: [61476.09094536 63573.30861552 62455.56557351 65110.79627573
 61476.09094536 63573.30861552 62455.56557351 65110.79627573
 61283.7893392  62647.86717968 62076.4982739  63287.69052768
 61517.23678438 62058.85704802 70718.50691485 61476.09094536
 63573.30861552 62455.56557351 65110.79627573 61283.7893392
 62647.86717968 62076.4982739  63287.69052768 61517.23678438
 62058.85704802 70718.50691485 61476.09094536 67707.92712237
 61884.19666773 61283.7893392  65988.18953453 61476.09094536
 61855.15824497 68060.03113699 62076.4982739  65984.41047454
 61476.09094536 68265.46924263 61884.19666773 61283.7893392
 65988.18953453 61476.09094536 62058.85704802 68060.03113699
 62076.4982739  65984.41047454 61476.09094536 68323.32510079
 62455.56557351 61283.7893392  65988.18953453 61476.09094536
 61283.7893392  68060.03113699 62076.4982739  65984.41047454
 61476.09094536 68265.46924263 61884.19666773 61283.7893392
 65988.18953453 61476.09094536 62058.85704802 68060.03113699
 62076.4982739  65984.41047454 61476.09094536 68265.46924263
 61884.19666773 61283.7893392  65988.18953453 61476.09094536
 62058.85704802 68060.03113699 62076.4982739  65984.41047454
 61476.09094536 68265.46924263 61884.19666773 61283.7893392
 65988.18953453 61476.09094536 62058.85704802 68060.03113699
 62076.4982739  65984.41047454 61476.09094536 68265.46924263
 61884.19666773 61283.7893392  65988.18953453 61476.09094536
 62058.85704802 68060.03113699 62076.4982739  65984.41047454
 61476.09094536 68265.46924263 61884.19666773 61283.7893392
 65988.18953453 61476.09094536 62058.85704802 68060.03113699
 62076.4982739  65984.41047454 61476.09094536 68265.46924263
 61884.19666773 61283.7893392  65988.18953453 61476.09094536
 62058.85704802 68060.03113699 62076.4982739  65984.41047454
 61476.09094536 68265.46924263 61884.19666773 61283.7893392
 65988.18953453 61476.09094536 62058.85704802 68060.03113699
 62076.4982739  65984.41047454 61476.09094536 68265.46924263
 61884.19666773 61283.7893392  65988.18953453 61476.09094536
 62058.85704802 68060.03113699 62076.4982739  65984.41047454
 61476.09094536 68265.46924263 61884.19666773 61283.7893392
 65988.18953453 61476.09094536 62058.85704802 68060.03113699
 62076.4982739  65984.41047454 61476.09094536 68265.46924263
 61884.19666773 61283.7893392  65988.18953453 61476.09094536]

In [4]:
def round_to_nearest_hundred(number):
    return round(number, -2)

In [5]:
prd_out_total_life_km = []
for i in predicted_output:
    prd_out_total_life_km.append(round_to_nearest_hundred(i))
print(len(prd_out_total_life_km))
print(prd_out_total_life_km)

152
[61500.0, 63600.0, 62500.0, 65100.0, 61500.0, 63600.0, 62500.0, 65100.0, 61300.0, 62600.0, 62100.0, 63300.0, 61500.0, 62100.0, 70700.0, 61500.0, 63600.0, 62500.0, 65100.0, 61300.0, 62600.0, 62100.0, 63300.0, 61500.0, 62100.0, 70700.0, 61500.0, 67700.0, 61900.0, 61300.0, 66000.0, 61500.0, 61900.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 62500.0, 61300.0, 66000.0, 61500.0, 61300.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0, 62100.0, 68100.0, 62100.0, 66000.0, 61500.0, 68300.0, 61900.0, 61300.0, 66000.0, 61500.0]